ecs/instances.go

add DescribeInstanceVncUrl API

add DescribeInstanceVncUrl API

---

util/util.go
util/util_test.go

add `GenerateRandomECSPassword` for #2

add GenerateRandomECSPassword

---

ecs/disks.go
ecs/images.go
ecs/instance_types.go
ecs/instances.go
ecs/monitoring.go
ecs/networks.go
ecs/regions.go
ecs/route_tables.go
ecs/security_groups.go
ecs/snapshots.go
ecs/vpcs.go
ecs/vrouters.go
ecs/vswitches.go

add links
You can see what is it like at https://godoc.org/github.com/yufeizyf/aliyungo/ecs

Add docs links for ecs. Docs at http://docs.aliyun.com/

---

ecs/disks.go
ecs/images.go
ecs/instance_types.go
ecs/instances.go
ecs/monitoring.go
ecs/networks.go
ecs/regions.go
ecs/route_tables.go
ecs/security_groups.go
ecs/snapshots.go
ecs/vpcs.go
ecs/vrouters.go
ecs/vswitches.go
ecs/zones.go

add ecs dateType docs links for aliyungo. Base on 2015e676203298ed72c…

add ecs dateType docs links for aliyungo.

---

ecs/config_test.go
ecs/disks.go
ecs/disks_test.go
ecs/instances.go
ecs/instances_test.go

add method ReplaceSystemDisk in disk.go to support reimage
add method ModifyInstanceAttribute in instance.go to modify password or instanceName or other attribute when the instance system disk replaced

Add method ReplaceSystemDisk and ModifyInstanceAttribute

---

ram/account.go
ram/account_test.go
ram/ak.go
ram/ak_test.go
ram/api.go
ram/client.go
ram/client_test.go
ram/error.go
ram/group.go
ram/group_test.go
ram/mfa.go
ram/policy.go
ram/policy_test.go
ram/profile.go
ram/profile_test.go
ram/role.go
ram/role_test.go
ram/security.go
ram/security_test.go
ram/types.go
util/encoding.go

implements parts of the basic ram sdk(account,policy and ak).

ram sdk implements

---

ram/ak_test.go
ram/api.go
ram/policy.go

fix %v and add ListPoliciesForUser 

---

ecs/instances.go

add_io_optimized_option

---

sls/client.go

workaround sls bug：通过API获取Project容易出现502，改成本地直接构造

---

ecs/config_test.go
ecs/instances.go
ecs/instances_test.go

新增JoinSecurityGroup和LeaveSecurityGroup方法

添加将实例加入和移除安全组的方法

---

sls/client.go
sls/client_test.go

Feature sls putlogs

---

rds/client.go
rds/monitoring.go

要用到RDS监控接口，发现没有SDK，就写了一个。第一次用github，不对的地方请指教

新增阿里云RDS 查看实例性能数据SDK

---

common/types.go
ecs/instances.go

根据ECS的API文档及Python SDK添加了一些新参数及返回字段。

新增ECS的部分新参数及返回字段

---

ecs/disks.go
ecs/instance_types.go

添加ECS磁盘及实例规格相关新字段
磁盘：
+ 付费类型
实例规格：
+ 实例规格族

添加ECS磁盘及实例规格相关新字段

---

dns/client.go
ecs/client.go
ram/client.go
rds/client.go
slb/client.go
sls/client.go

endpoint优先级：code > env > default
Signed-off-by: 姜继忠 <jizhong.jiangjz@aliaba-inc.com>

支持从环境变量获取endpoint

---

README.md
common/regions.go
ram/ak.go
ram/api.go
ram/role.go
ram/role_test.go
ram/types.go
sls/client.go

I am using aliyungo in my project and found role is actually not supported so I just added it and thought it should be useful.
Changes:
1. Added RAM Role Support
2. Added corresponding unit tests
Please help review the code and let me know if there is anything I should change here. Thanks!

Added Ram Role support

---

sls/client_test.go
sls/logtail.go

ilogtail will transfer hostname, userid and etc.

add enable_tag in logtail config.

---

dm/mail.go
dm/sms.go

抱歉，有一个import地址的问题。修正import地址到原来的repo，这用使用者不需要pull我的repo

use the main repo's util import address

---

ecs/instances.go

I think so.
Though it dose not affect the program to run.

fix miss-spelling

---

ecs/images.go

imporve image attribution according to api response

improve image attribution

---

ecs/instance_types.go

add new method describeInstanceTypesNew support parameter

describeInstanceTypes add paramter

---

ecs/instances.go

Minor API changes: instance status, ModifiyInstanceAttribute

---

nas/CreateAccessRule.go
nas/CreateFileSystem.go
nas/CreateMountTarget.go
nas/DescribeAccessRules.go
nas/DescribeFileSystems.go
nas/DescribeMountTargets.go
nas/client.go

add 6 interface of nas sdk;
others will be ok in the next merge.

add part of nas sdk

---

dm/mail.go

Based on Aliyun dm document ReplyToAddress should be bool.
https://help.aliyun.com/document_detail/29444.html?spm=5176.doc29434.6.569.7rc147

ReplyToAddress: bool

---

slb/rules.go

@denverdino 
ref https://github.com/denverdino/aliyungo/issues/119

slb:add omitempty json tag for Rule

---

ecs/client.go
ecs/security_groups.go
rds/client.go
slb/servers.go

init slb, rds and vpc client endpoint by regionId

init client endpoint by regionId

---

ecs/nat_gateway.go
ecs/nat_gateway_test.go
ecs/snat_entry.go
ecs/snat_entry_test.go

add snat and update natgateway to support snat entry

Feature snat

---

common/client.go
ess/client.go
ess/config_test.go
ess/configuration.go
ess/configuration_test.go
ess/group.go
ess/group_test.go
ess/rule.go
ess/rule_test.go
ess/schedule.go
ess/schedule_test.go
util/encoding.go

1. add ess related interface include scalinggroup, scalingconfiguration, rule and schedule.
2. support special key name style

support ess

---

ecs/vpcs.go
ecs/vswitches.go

Add vpc and vswitch new attribution 'IsDefault'

Add the attribution of vpc and vswitch IsDefault

---

ecs/instances.go
rds/instances.go
slb/listeners.go

improve WaitForInstanceAsyn in the ecs/instances.go
add WaitForInstanceAsyn in the rds/instances.go
add WaitForListenerAsyn in the slb/listeners.go

improve WaitForInstanceAsyn and add WaitForListenerAsyn

---

common/client.go

Add User-Agent for Request Header and it can help user to define user-agent.

Add User-Agent for Request Header

---

ecs/zones.go

modify AvaliableResourceType field's map key to SupportedResourceType

modify avaliableResourceType map key to SupportedResourceType

---

ecs/vswitches.go
rds/instances.go
slb/listeners.go

The PR adds region id while describing vswitches, improves DBInstanceAttribute, TCPListenerType and UDPListenerType.

add some parameters for request and response

---

ecs/instances.go

add keypairname for instance attribute

add keypairname for instance attribute

---

ram/api.go
ram/group.go
ram/group_test.go
ram/mfa.go
ram/mfa_test.go
ram/policy.go
ram/policy_test.go
ram/profile.go
ram/profile_test.go
ram/security.go
ram/security_test.go
ram/types.go

1、add LoginProfile interface and test case.
2、add MFAdevice interface and test case.
3、add Group manage interface and test case.
4、add SecuritySet interface and test case.
5、complete Policy interface and test case.

complete some interface and fix bug with new function.

---

ecs/instances.go

add keyname for CreateInstanceArgs

add keyname for CreateInstanceArgs

---

rds/instances.go

The PR mainly improve rds instance and as following:
1. update Error Code when describe rds attribute;
2. add new function that can reset rds account password

add function to reset rds account password

---

cs/client.go
cs/clusters.go

The PR mainly solves the following issues:
1. Add user agent for container's client;
2. Improve container cluster's state code according response;
3. Add new function to resize cluster;
4. Add new function to wait for cluster's state has become expected.

improve containers cluster and add function to reset cluster size

---

cdn/client.go
cdn/client_test.go
cdn/config.go
cdn/config_test.go
cdn/domain.go
cdn/domain_test.go
cdn/refresh.go
cdn/service.go
cdn/types.go

add interface for domain, domain config, refresh, cdn service.

CDN:  add interface for domain, domain config, refresh, cdn service.

---

ecs/instances.go
ecs/instances_test.go

AttachInstanceRamRole
DetachInstanceRamRole
DescribeInstanceRamRole

add interface for instance ram role.

---

ram/policy.go

add const paramter for policy type.

add const paramter for policy type.

---

ess/group.go

ess: add AttachInstances and RemoveInstances for scaling group.

ess:add AttachInstances and RemoveInstances for scaling group.

---

ess/configuration.go

add DeactivateScalingConfiguration

add DeactivateScalingConfiguration

---

ecs/instances.go

add RamRoleName for CreateInstanceArgs.

add RamRoleName for CreateInstanceArgs.

---

ecs/router_interface.go
ecs/router_interface_test.go

add interface for router interface.

add interface for router interface.

---

ecs/networks.go

fix bug of ModifyInstanceNetworkSpec by modify InternetMaxBandwidthOut and InternetMaxBandwidthIn type

fix bug of ModifyInstanceNetworkSpec

---

README.md
cs/clusters.go
cs/projects.go
cs/projects_client.go
cs/services.go
cs/volumes.go

Add container service API support:
1. Volume API
2. Project API
3. Volume API

add container service project api sdk

---

ecs/disks.go

创建云盘添加 磁盘加密 参数
api文档：
https://help.aliyun.com/document_detail/25513.html

Add Encrypted field to CreateDiskArgs

---

cs/services.go
rds/instances.go

1. add cs.Container struct
2. replace rds CreateOrder(discard) to CreateDBInstance

improve cs.Service struct's container info and fix RDS Create instance API

---

ess/rule.go
ess/rule_test.go

Add ESS API for ~~`AttachInstances/DeleteInstances/`~~`ExecuteScalingRule`
Signed-off-by: Crazykev <crazykev@zju.edu.cn>

Add ExecuteScalingRule ESS API

---

ess/group.go

Signed-off-by: Crazykev <crazykev@zju.edu.cn>

use corresponding variable in RemoveInstances API

---

ess/group.go
util/encoding.go

For #193 
Signed-off-by: Crazykev <zhuyou.zh@alibaba-inc.com>

make MaxSize/MinSize int pointer to distinguish zero value from unset

---

ess/configuration.go
ess/group.go

add key pair, ram role and userdata for scaling configuration

improve ess configuration

---

ecs/disks.go
ecs/disks_test.go

add ResizeDisk method

---

common/regions.go

Add support for new AP-SouthEast-3 region

Add Ap-Southeast-3 (Malaysia)

---

common/regions.go
ecs/router_interface.go
ess/group.go

add WaitRouterInterface method to ensure new router interface is available; 
Set MinSize, MaxSize and DefaultCooldown type to int pointer to distinguish zero value from unset value

add wait routerinterface; modify ess group int type; add new region

---

metadata/client.go

https://github.com/rancher/rancher/issues/10439

Fix the issue that metadata API will be broken if status code is not 200

---

ecs/instances.go

使用ModifyInstanceAutoReleaseTime命令设置实例的自动释放时间

添加设置自动释放时间

---

metadata/client.go
metadata/client_test.go

1. metadata support get sts token. 
2. make metadata client concurrent…able

metadata client support sts token

---

ecs/networks.go

https://help.aliyun.com/document_detail/36072.html?spm=5176.doc36018.2.4.UBnilS

EipAdressSetType should have InstanceType

---

common/endpoints.xml
common/regions.go
oss/regions.go

add support for newly release region, cn-huhehaote

add region cn-huhehaote

---

common/types.go
ecs/instances.go

1. support to modify instance spec including instnaceType, bandwidth;
2. support to modify privateIp and vswitch;
3. support to modify instance charge type

support to modify instance spec, privateIp and charge type

---

slb/loadbalancers.go

add new method that inputting region id to get correct slb attribute

add new method to describe slb attribute

---

rds/instances.go

1. add WaitForDBConnection method to ensure allocating connection successfully;
2. add WaitForAccountPrivilegeRevoked method to ensure privilege has been revoked successfully;
3. add ModifyDatabaseDescription method to modify database description
4. add ReleaseInstancePublicConnection to release db connection
5. add SwitchDBInstanceNetType to allocate intranet connection

add some method to manage rds

---

oss/client.go

参考  x-oss-object-acl  参数设置
https://help.aliyun.com/document_detail/31978.html?spm=5176.doc31959.6.881.ty4TEU

修复上传对象权限KEY设置错误

---

circle.yml

Change-Id: I945dbc7202d7ef7f0a67e2a63767b1c41cf712ee

Fix circle-ci

---

ecs/disks.go

API Doc: https://help.aliyun.com/document_detail/25626.html

Add Encrypted field in DiskItemType

---

common/client.go
cs/client.go
cs/signature.go
rds/instances.go
rds/instances_test.go

1. add rds.DescribeDBInstances
2. remove debug info

add rds DescribeDBInstances, remove debug info

---

sls/logtail.go

update sls sdk to support delimiter config

update sls sdk to support delimiter config

---

slb/loadbalancers.go

add slb DescribeLoadBalancersArgs tags field

---

metadata/client.go

metadata support env METADATA_ENDPOINT

---

acm/acm.go
acm/acm_test.go
acm/coding.go
acm/coding_test.go

Add aliyun  acm sdk
unit test must add namespace `test` in aliyun account

add aliyun acm sdk

---

common/endpoint.go

output log when get service endpoint fail

---

ecs/eni.go

Add ENI status set length check. Fix #294

---

push/push.go

Add AndroidPopupActivity to push args

---

ecs/images.go

Support ecs image force delete #300

Add the force parameter when delete image

---

common/regions.go
common/regions_test.go

Add function to validate region

---

cs/clusters.go
cs/clusters_test.go

add NodeCIDRMask, LoggingType, SLSProjectName to kubernetes cluster

---

common/endpoint.go
common/endpoints.xml
common/regions.go
oss/regions.go

Hi--,
this adds support for recently launched UK region.

added UK region (eu-west-1)

---

cs/clusters.go
cs/clusters_test.go

Changes:
* Support ImageID to be set when creating a cluster.
* Support PrePaid Instances
* Add Managed Kubernetes test cases
* Add some constants for convenience.

New features to Kubernetes Clusters: image_id, prepaid instances, managed kubernetes

---

ecs/eni.go
ecs/eni_test.go
ecs/instance_types.go

Signed-off-by: bingshen.wbs <bingshen.wbs@alibaba-inc.com>

add eni private ip addresses support

---

ecs/vpcs.go

VpcSetType.RouterTableIds.RouterTableIds

---

ecs/eni.go
ecs/eni_test.go

Signed-off-by: bingshen.wbs <bingshen.wbs@alibaba-inc.com>

Add recently fields of eni response

---

pvtz/records.go

It may be just a typo, I think.

Fix pvtz UpdateZoneRecord api

---

slb/config_test.go
slb/listerners_test.go
slb/loadbalancers_test.go
slb/servers.go
slb/servers_test.go
slb/vserver_group_test.go

fixed slb.RemoveBackendServers not support ENI type backends

fixed slb.RemoveBackendServers not support ENI type backends

---

ecs/disks.go

fix issue: [#338 ](https://github.com/denverdino/aliyungo/issues/338)

support KMSKeyID arg in CreateDiskArgs

---

ros/client.go

add ros version

---

ecs/eni.go
ecs/eni_test.go

Signed-off-by: bingshen.wbs <bingshen.wbs@alibaba-inc.com>

add filter eni by private ips

---

ecs/route_tables.go
ecs/route_tables_test.go

1. fix typo in NextHopType, **NextHopIntance -> NextHopInstance, NextHopTunnelRouterInterface -> NextHopRouterInterface**
2. add some new types
ref to [docs](https://help.aliyun.com/document_detail/36012.html?spm=a2c4g.11174283.6.626.622c6dd4tLs8R4)

modify NextHopTypes

---

common/endpoint.go

fix concurrent map write problems

---

ecs/route_entry.go

add route client DescribeRouteEntryList API

---

ecs/disks.go

support ecs tag

---

ecs/eni.go
ecs/eni_test.go

https://help.aliyun.com/document_detail/58504.html

support eniip on eni create

---

ecs/vpcs.go

https://help.aliyun.com/document_detail/35739.html?spm=a2c4g.11186623.6.672.7f241fc2hxQ1Hi

support multi CIDR vpc

---

cen/client.go
cen/route.go

cen support

---

cen/route.go

add pagenition

---

cs/kubernets_cluster.go

add cluster args for serviceaccount volume projection and custom san

add cluster args for serviceaccount volume projection and custom san

---

ros/signature.go

conditional log

---

ros/other.go

add status for event

---

ros/standard/client.go
ros/standard/client_test.go
ros/standard/stack.go

add new ros api

---

ros/standard/stack.go

resource attributie

---

ros/standard/stack.go

switch request & response stack

---

ros/standard/client_test.go
ros/standard/stack.go

fix create stack parameter

---

ess/configuration.go
ess/group.go

ess modify scaling configuration

---

ess/group.go

scaling activities fix

---

ess/group.go
ess/group_test.go

fix scaling field & test

---

cs/kubernets_cluster.go
cs/serverless.go

update cluster creation parameter: ResourceGroupId

update cluster creation parameter: ResourceGroupId

---

cs/clusters.go

add profile field to identify Edge cluster type

add profile field to identify Edge cluster type

---

ecs/instance_types.go
ecs/instance_types_test.go

```
+	InstanceTypes      []string `query:"list"`
```

add new DescribeInstanceTypes args

---

cs/clusters.go
cs/kubernets_cluster.go
cs/node_pool.go

- GetKubernetesClusterNodes support get node pool nodes
- Create Cluster Args 
- Create nodepool Args

The parameters are aligned with the ack

---

cs/clusters.go

fix bug:GetKubernetesClusterNodes

---

cs/kubernets_cluster.go

CreateCluster support MaintenanceWindow

---

common/client.go

now we can only set TLS timeout to http client. If we want to set other timeout to http client, we can't find any method. 
In our project, we invoke aliyun api across counties，for example from Singapore to China. We always meet different kind of timeout because of the net unstable. So we want to set different kind of timeout.
This pr add env to other four env to set different kind of timeout.

add envs to set http timeout

---

slb/loadbalancers.go
slb/loadbalancers_test.go

1. Add Api: ServiceManagedControl
2. Add Attribute to LoadBalancerType which represent the managed status of slb resources

extend slb api to support "ServiceManaged"

---

acm/acm.go
acm/acm_test.go

fix: fix acm GetAllConfigs error

---

cs/node_pool.go

ACK node pool support desired node size

ACK node pool support desired node size

---

cs/serverless.go

Add snat_entry parameter for serverless cluster

Add snat_entry parameter for serverless cluster

---

cs/serverless.go

Change the type of parameter snat_entry

Change the type of parameter snat_entry

---

common/client.go
common/client_test.go

support custom header

---

cs/client.go

cs client support header x-acs-proxy-source-ip and x-acs-proxy-secure-transport

cs client support header x-acs-proxy-source-ip and x-acs-proxy-secure-transport

---

cs/client.go

change http header name x-acs-source-ip and x-acs-secure-transport

change http header name x-acs-source-ip and x-acs-secure-transport

---

cs/kubernets_cluster.go

Add parameters to cluster information.

Add parameters to cluster information

---

cs/node_pool.go

add polardb support

---

ros/client.go

Get ros endpoint from env

---

ecs/client_test.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>

delete minor unreachable code caused by t.Fatal

---

ros/client.go

ros client supports custom headers

Feature: ros client supports custom headers
