denverdino/aliyungo

- oss/client.go
https://docs.aliyun.com/#/pub/oss/api-reference/bucket&GetBucket 
文档写的是“限定此次返回object的最大数，如果不设定，默认为100，max-keys取值不能大于1000。”，代码里的注释写错了。
@denverdino Plz review, thx!
> Fix a number error in doc: oss.Bucket.List

- ecs/instances.go
fix #52
remove const `ecs.LockReasonFinancial`, `ecs.LockReasonSecurity` because ecs.LockReason  is struct type now.
> fix ecs.LockReason unmarshal error

- ecs/instances.go
When my app run in one aliyun instance, my app want to get the InstanceID of this instance, so I want to `DescribeInstances` by `RegionId` and `InstanceName`. The `InstanceName` is the `hostname`   of the local instance.  
This is why I add `InstanceName` in `DescribeInstancesArgs` struct.
> add InstanceName for search request

- oss/client.go
- oss/signature.go
- sts/assume_role.go
- sts/assume_role_test.go
- sts/client.go
- sts/client_test.go
1. STS support itself with unit tests
2. light Integration with oss client. I had a test locally:
a. create a role for assume which only has oss:GetObject prolicy attached
b. assume this role with object prefix policy
c. files could be downloaded successfully
Once again, any comments is welcomed and let me know if you think any further modification in this pull request is required, thanks!
> Added STS support with unit tests

- oss/client.go
oss team suggest maxCopySize better be 128MB
> oss team suggest maxCopySize could be set to 128MB

- metadata/client.go
- metadata/client_test.go
Include metadata blow
```
RS_TYPE_META_DATA = "meta-data"
RS_TYPE_USER_DATA = "user-data"
DNS_NAMESERVERS    = "dns-conf/nameservers"
EIPV4              = "eipv4"
HOSTNAME           = "hostname"
IMAGE_ID           = "image-id"
INSTANCE_ID        = "instance-id"
MAC                = "mac"
NETWORK_TYPE       = "network-type"
NTP_CONF_SERVERS   = "ntp-conf/ntp-servers"
OWNER_ACCOUNT_ID   = "owner-account-id"
PRIVATE_IPV4       = "private-ipv4"
REGION             = "region-id"
SERIAL_NUMBER      = "serial-number"
SOURCE_ADDRESS     = "source-address"
VPC_CIDR_BLOCK     = "vpc-cidr-block"
VPC_ID             = "vpc-id"
VSWITCH_CIDR_BLOCK = "vswitch-cidr-block"
VSWITCH_ID         = "vswitch-id"
```
**Note:** metadata client only available under aliyun vpc network
Signed-off-by: yaoyao.xyy …
> Add vpc metadata client support

- common/client.go
- slb/listeners.go
- slb/loadbalancers.go
issue #87 ECS use internetchargetype is PayByBandwidth | PayByTraffic,
but SLB is paybybandwidth | paybytraffic , so I use a new type in SLB with the same name.
add gzip in create http or https or tcp(health check http)
add a func for encode mutiple healthcheckcode
fix a bug in client.Invoke(httpReq may be nil)
> internetchargetype in slb && gzip && healthchecktype && revivew bug

- slb/loadbalancers.go
Add field LoadBalancerName to struct DescribeLoadBalancersArgs to enable search by LB name.
> Add field LoadBalancerName to struct DescribeLoadBalancersArgs

- dm/mail.go
https://help.aliyun.com/document_detail/29444.html?spm=5176.doc29435.2.1.eHTlk0
使用的时候发现别名用不了，翻代码发现有个小命名错误 :)
> fix incorrect field name FormAlias to FromAlias

- ecs/disks.go
- ecs/forward_entry.go
- ecs/images.go
- ecs/instances.go
- ecs/nat_gateway.go
- ecs/networks.go
- ecs/route_tables.go
- ecs/security_groups.go
- ecs/snapshots.go
- ecs/snat_entry.go
- ecs/ssh_key_pair.go
- ecs/tags.go
- ecs/vpcs.go
- ecs/vrouters.go
- ecs/vswitches.go
- ecs/zones.go
ECS 的 Describe API 中所有带分页功能的接口原来的返回的都不是原生的 response 信息，返回信息中把 common.Response （requestId）信息都丢失了。所以对 ECS 的 Describe API 添加了 DescribexxxWithRaw 函数返回原生的 Response 信息
> add DescribeXXXWithRaw get raw response info

- ecs/zones.go
The PR add a new item 'AvailableResources' in which 'DescribeZones' response, and using it can get supported resources in the one zone.
> Add AvailableResources of DescribeZones response

- cdn/types.go
CDN API valid source type should be "ipaddr", "domain" and  "oss".
> modify cdn source type OSS to oss

- rds/instances.go
- rds/monitoring.go
主数据库可以有多个只读库，所以 ReadOnlyDBInstanceId 应该要修改，例如有一个只读库时：
"ReadOnlyDBInstanceIds":{"ReadOnlyDBInstanceId":[{"DBInstanceId":"rr-bpxxxxxxx"}]}
> 第一、ReadOnlyDBInstanceId 的类型应该是数组（RDS 有只读实例时），第二、DescribeDBInstancePerformanceArgs的 key 首字母应该大写

- common/client.go
- common/request.go
- ecs/client.go
- ram/client.go
- sts/assume_role_test.go
- sts/client.go
- sts/get_caller_identity.go
- sts/get_caller_identity_test.go
1. Support to create Clients from credentials of assumed role and fix issue #204.
2. Add API: sts.STSClient.GetCallerIdentity().
3. Add RegionID as request parameter.
> Support to create Clients from credentials of assumed role

- dns/AddDomainRecord.go
- dns/DescribeDomainRecordInfoNew.go
The type of priority is Long in the API, and modify it to int32 for matching
> modify priority type

- metadata/client.go
ECS now support get role name from metadata.
I can verify from my instance.
```sh
[root@iZuf69q0vgob6j1o2ncw3bZ ~]# curl http://100.100.100.200/latest/meta-data/ram/security-credentials/
DevDefault
```
> add RoleName to metadata

- ess/group.go
ScalingGroup support multiple vswitchs, the SDK miss  parameter VSwitchIds to support creating ScalingGroup with multiple vswitch, as well as describing ScalingGroup.
> add parameter VSwitchIds

- ess/configuration.go
Enabling setting InternetMaxBandwitdh to 0 so we can create scaling group instances without public IP
> Enable InternetMaxBandwitdh=0

- ecs/disks.go
Parameter ‘Name’ can not be identified, modify to 'DiskName'.
> update DiskName parameter

- cs/client.go
- oss/client.go
if we do not add header `x-acs-version`, it will response as following.
```json
{
"Recommend": "https://error-center.aliyun.com/status/search?Keyword=InvalidAction.NotFound&source=PopGw",
"Message": "Specified api is not found, please check your url and method.",
"RequestId": "0C922E89-2F00-41CE-AB9F-8014157F9B2E",
"HostId": "cs.aliyuncs.com",
"Code": "InvalidAction.NotFound"
}  
```
> Fix cs api call failure issue, move some debug info into debug mode.

- common/client.go
aliyun apsara stack do not have location service, so we use Environment Parameter XXX_ENDPOINT to set product endpoint.
> add flag for aliyun apsara stack env to skip location service

- cs/clusters.go
- cs/clusters_test.go
Added support for Kubernetes Cluster MultiAZ creation.
Cluster creation's API style had been changed, most parameters are now placed under the root key, instead of the `stack_params` key.
So I made a new method `CreateKubernetesMultiAZCluster` and a new struct `KubernetesMultiAZCreationArgs`  to create multiaz cluster, not touching the old-sytle API.
API Doc is located at https://help.aliyun.com/document_detail/73987.html
> support kubernetes cluster multiaz creation

- cs/clusters.go
- cs/clusters_test.go
What I've changed:
* Mark `KubernetesStackArgs`,`ResizeKubernetes` as deprecated
* Add `KubernetesVersion`, `Network` to `KubernetesMultiAZCreationArgs`
* Add `DescribeKubernetesCluster` to get details about a kubernetes cluster
* Add `ResizeKubernetesCluster` to support resizing of singleAZ/multiAZ cluster
> support new-style api for container service

- cs/clusters.go
- cs/clusters_test.go
When creating a k8s cluster, setting bool to false will cause marshaled json ignore this bool, so I removed these 'omitempty'.
And I added PublicSLB to k8s creation and describe.
> Add PublicSLB arg to K8S, remove lots of 'omitempty'

- oss/client.go
- oss/signature.go
- util/util.go
When we need SignedURL for AssumeRole, we need to pass STS Token in the URL, not in the header.
SignedURLWithMethodForAssumeRole will read the STS Token out, put it in the URL.
All params in ossParamsToSign are sub-resource, sub-resource should not be URL escaped.
See
https://help.aliyun.com/document_detail/31951.html
https://help.aliyun.com/document_detail/31952.html
https://help.aliyun.com/document_detail/31953.html
> add SignedURLWithMethodForAssumeRole for Registry

- cdn/auth/random_uuid.go
- cdn/auth/random_uuid_test.go
- cdn/auth/sign_url.go
- cdn/auth/sign_url_test.go
This PR enable Aliyun CDN user to sign url with A, B or C type auth method. Test cases refer to https://help.aliyun.com/document_detail/85116.html
> add cdn auth utility

- cs/clusters.go
- cs/clusters_test.go
When cluster in unready status, bool values are not set, DescribeKubernetesCluster will return an error.
If we change those bool values to *bool, we can set to nil pointers and let user determine how to deal with.
> change cs's bool parameter to *bool

- cs/clusters.go
- cs/clusters_test.go
The parseBoolOrNil is problematic, the second arg is a pointer, cannot be changed inside the function. So this function is not working at all.
Run the unit test again, saw it working now.
> fix parseBoolOrNil in cs

- acm/acm.go
- acm/acm_test.go
Aliyun changed ACM service respond encoding format from GBK to UTF-8, this PR fixed the related issue and refined the unit test.
> fix: fix acm GBK decoding error due to aliyun changed respond encode

- cs/clusters.go
- cs/clusters_test.go
Container Service no longer returns Parameters when describing a cluster, so aliyungo should not read from Parameters any more.
WorkerInstanceTypes and VSwitchIds is added when creating a new cluster.
And a new ScaleKubernetesCluster function is added.
Signed-off-by: xh4n3 <xyn1016@gmail.com>
> remove parameters and add scale api

- ecs/snat_entry.go
- ecs/snat_entry_test.go
try to support SourceCIDR field to CreateSnatEntry, ref to [official docs](https://help.aliyun.com/document_detail/120259.html?spm=a2c4g.11186623.6.612.599c4078PDkIPn) .
> Support SourceCIDR field to CreateSnatEntry

- cms/client.go
- cs/client.go
- cs/projects_client.go
- mns/client.go
- oss/client.go
- ros/client.go
- sls/client.go
Use this method to give users more control of httpClient. #369
> Add SetTransport method for other Client structs

- ecs/eni.go
- ecs/eni_test.go
ref to [docs](https://help.aliyun.com/document_detail/58513.html?spm=a2c4g.11174283.6.1350.738e52fed8Wlf4)
SecurityGroupId field should have `query:"list"` tag to avoid to be marshaled to a json string slice.
Signed-off-by: Bruce Ma <brucema19901024@gmail.com>
> modify tags for SecurityGroupId field in ModifyNetworkInterfaceAttributeArgs

- cs/clusters.go
Add three edge kubernetes related params to support scaling Alicloud ENS node as worker into edge cluster.
> Add edge kubernetes related params to support scaling Alicloud ENS node

- .travis.yml
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.
> Added power support to CI

- oss/client_test.go
- oss/signature.go
Traffic limitings in OSS SignedURL are not currently supported in aliyungo, we should allow `x-oss-traffic-limit` to be included in url params signature calculation.
See https://help.aliyun.com/document_detail/124583.html
> include x-oss-traffic-limit in url signature

- ecs/eni.go
- ecs/eni_test.go
`AssignPrivateIpAddresses` in ECS is now return `AssignedPrivateIpAddressesSet`
See https://help.aliyun.com/document_detail/85917.html
> support AssignPrivateIpAddresses in sync mode
